#!/usr/bin/env python3
"""Generate the ESP32 bitmap font header from GNU Unifont's Taiwan variant."""

from __future__ import annotations

import gzip
import io
import urllib.request
from pathlib import Path


UNIFONT_VERSION = "17.0.04"
SOURCE_URL = (
    "https://ftp.gnu.org/gnu/unifont/"
    f"unifont-{UNIFONT_VERSION}/unifont_t-{UNIFONT_VERSION}.bdf.gz"
)
OUTPUT = Path(__file__).with_name("cjk16_font.h")

# Korean and CJK characters used by Spotify metadata and LRCLIB lyrics. Keeping
# these as dense ranges gives the ESP32 constant-time bitmap lookup and avoids
# the incomplete Korean subset supplied by U8g2. Thai stays in U8g2's complete
# 182-glyph ETL TIS-620 font because those glyphs use narrower bitmap cells.
RANGES = (
    (0x1100, 0x11FF),  # Hangul Jamo
    (0x3131, 0x318E),  # Hangul Compatibility Jamo
    (0x3400, 0x9FFF),
    (0xAC00, 0xD7A3),  # Every modern precomposed Hangul syllable
    (0xF900, 0xFAFF),
)


def download_bdf() -> str:
    with urllib.request.urlopen(SOURCE_URL) as response:
        compressed = response.read()
    return gzip.decompress(compressed).decode("utf-8")


def parse_glyphs(bdf: str) -> dict[int, bytes]:
    glyphs: dict[int, bytes] = {}
    code_point: int | None = None
    bitmap_rows: list[str] = []
    reading_bitmap = False

    for raw_line in io.StringIO(bdf):
        line = raw_line.strip()
        if line.startswith("ENCODING "):
            code_point = int(line.split()[1])
            bitmap_rows = []
            reading_bitmap = False
        elif line == "BITMAP":
            reading_bitmap = True
        elif line == "ENDCHAR":
            if code_point is not None and len(bitmap_rows) == 16:
                glyph = bytes.fromhex("".join(bitmap_rows))
                if len(glyph) == 32:
                    glyphs[code_point] = glyph
            code_point = None
            reading_bitmap = False
        elif reading_bitmap:
            bitmap_rows.append(line)

    return glyphs


def generate_header(glyphs: dict[int, bytes]) -> str:
    selected: list[tuple[int, bytes]] = []
    range_offsets: list[int] = []

    for first, last in RANGES:
        range_offsets.append(len(selected))
        for code_point in range(first, last + 1):
            try:
                selected.append((code_point, glyphs[code_point]))
            except KeyError as error:
                raise RuntimeError(f"Unifont is missing U+{code_point:04X}") from error

    lines = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "// Generated by generate_cjk16_header.py from GNU Unifont's Taiwan",
        f"// variant {UNIFONT_VERSION}. The glyph data is licensed under the SIL Open",
        "// Font License 1.1; see UNIFONT-OFL-1.1.txt in this sketch folder.",
        "// Includes all modern Korean syllables and BMP Chinese ideographs.",
        "// Do not edit this generated file by hand.",
        "",
        "constexpr uint8_t CJK16_GLYPH_WIDTH = 16;",
        "constexpr uint8_t CJK16_GLYPH_HEIGHT = 16;",
        "constexpr uint8_t CJK16_BYTES_PER_GLYPH = 32;",
        f"constexpr uint8_t CJK16_RANGE_COUNT = {len(RANGES)};",
        "",
        "const uint16_t CJK16_RANGE_FIRST[CJK16_RANGE_COUNT] PROGMEM = {",
        "  " + ", ".join(f"0x{first:04X}" for first, _ in RANGES),
        "};",
        "const uint16_t CJK16_RANGE_LAST[CJK16_RANGE_COUNT] PROGMEM = {",
        "  " + ", ".join(f"0x{last:04X}" for _, last in RANGES),
        "};",
        "const uint32_t CJK16_RANGE_OFFSET[CJK16_RANGE_COUNT] PROGMEM = {",
        "  " + ", ".join(f"{offset}UL" for offset in range_offsets),
        "};",
        "",
        f"const uint8_t CJK16_BITMAPS[{len(selected) * 32}UL] PROGMEM = {{",
    ]

    for code_point, glyph in selected:
        encoded = ", ".join(f"0x{value:02X}" for value in glyph)
        lines.append(f"  {encoded},  // U+{code_point:04X}")

    lines.extend(("};", ""))
    return "\n".join(lines)


def main() -> None:
    glyphs = parse_glyphs(download_bdf())
    OUTPUT.write_text(generate_header(glyphs), encoding="ascii", newline="\n")
    print(f"Generated {OUTPUT} ({OUTPUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
